/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/verb_learning/srv/ForgetVerb.srv.  Do not edit! */
package ros.pkg.verb_learning.srv;

import java.nio.ByteBuffer;

public class ForgetVerb extends ros.communication.Service<ForgetVerb.Request, ForgetVerb.Response> 
{

public static String __s_getDataType() { return "verb_learning/ForgetVerb"; }
public static String __s_getMD5Sum() { return "8763f05b492b0435c0d2c68a6e4263b5"; }

public String getDataType() { return ForgetVerb.__s_getDataType(); }
public String getMD5Sum() { return ForgetVerb.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public ros.pkg.verb_learning.msg.VerbDescription verb;

  public Request() {
 super();
    verb = new ros.pkg.verb_learning.msg.VerbDescription();

  }
  public static java.lang.String __s_getDataType() { return "verb_learning/ForgetVerbRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "verb_learning/VerbDescription verb\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("8763f05b492b0435c0d2c68a6e4263b5"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("verb_learning/ForgetVerb"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
      verb = (ros.pkg.verb_learning.msg.VerbDescription)verb.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("verb", "ros.pkg.verb_learning.msg.VerbDescription");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.verb_learning.msg.VerbDescription");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    verb = __m2.verb;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += verb.serializationLength(); // verb
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
     verb.serialize(bb, seq);
  }
  public void deserialize(ByteBuffer bb)  {
     verb.deserialize(bb);
  }
}

public static class Response extends ros.communication.Message
{


  public Response() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "verb_learning/ForgetVerbResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "================================================================================\n" + 
    "MSG: verb_learning/VerbDescription\n" + 
    "string verb\n" + 
    "string[] arguments\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("8763f05b492b0435c0d2c68a6e4263b5"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("verb_learning/ForgetVerb"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
  }
  public void deserialize(ByteBuffer bb)  {
  }
}

public ForgetVerb.Request createRequest() { return new ForgetVerb.Request(); }public ForgetVerb.Response createResponse() { return new ForgetVerb.Response(); }}

