/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/verb_learning/srv/LoadVerbs.srv.  Do not edit! */
package ros.pkg.verb_learning.srv;

import java.nio.ByteBuffer;

public class LoadVerbs extends ros.communication.Service<LoadVerbs.Request, LoadVerbs.Response> 
{

public static String __s_getDataType() { return "verb_learning/LoadVerbs"; }
public static String __s_getMD5Sum() { return "4e7975af5e80f5adfb11c0c812ce9640"; }

public String getDataType() { return LoadVerbs.__s_getDataType(); }
public String getMD5Sum() { return LoadVerbs.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{


  public Request() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "verb_learning/LoadVerbsRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("4e7975af5e80f5adfb11c0c812ce9640"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("verb_learning/LoadVerbs"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
  }
  public void deserialize(ByteBuffer bb)  {
  }
}

public static class Response extends ros.communication.Message
{

  public ros.pkg.verb_learning.msg.VerbDescription[] verbs;

  public Response() {
 super();
  verbs = new ros.pkg.verb_learning.msg.VerbDescription[0];

  }
  public static java.lang.String __s_getDataType() { return "verb_learning/LoadVerbsResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "verb_learning/VerbDescription[] verbs\n" + 
    "================================================================================\n" + 
    "MSG: verb_learning/VerbDescription\n" + 
    "string verb\n" + 
    "string[] arguments\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("4e7975af5e80f5adfb11c0c812ce9640"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("verb_learning/LoadVerbs"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
      verbs =  (ros.pkg.verb_learning.msg.VerbDescription[])(clone.verbs.clone());
      for (int i = 0; i < verbs.length; i++) verbs[i] = (ros.pkg.verb_learning.msg.VerbDescription)verbs[i].clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("verbs", "ros.pkg.verb_learning.msg.VerbDescription[]");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.verb_learning.msg.VerbDescription");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    verbs = __m2.verbs;
    }

  int calc_verbs_array_serialization_len() {
    int l = 0;
    for (int i = 0; i < verbs.length; i++) 
      l += verbs[i].serializationLength();
    return l;
  }
  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + calc_verbs_array_serialization_len(); // verbs
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    bb.putInt(verbs.length);
    for (ros.pkg.verb_learning.msg.VerbDescription x : verbs)
      x.serialize(bb, seq);
  }
  public void deserialize(ByteBuffer bb)  {
     int verbs_len = bb.getInt();
    verbs = new ros.pkg.verb_learning.msg.VerbDescription[verbs_len];
    for(int i = 0; i < verbs_len; i++)
      {verbs[i] = new ros.pkg.verb_learning.msg.VerbDescription(); verbs[i].deserialize(bb); }
  }
}

public LoadVerbs.Request createRequest() { return new LoadVerbs.Request(); }public LoadVerbs.Response createResponse() { return new LoadVerbs.Response(); }}

