TrajectoryPlannerROS:
    # Robot Configuration Parameters
    acc_lim_x: 1.0
    acc_lim_y: 1.0
    acc_lim_th: 1.0
    max_vel_x: 0.25
    min_vel_x: 0.05
    max_rotational_vel: 0.8
    min_in_place_rotational_vel: 0.3
    escape_vel: -0.1
    holonomic_robot: false

    # Goal Tolerance Parameters
    xy_goal_tolerance: 0.1
    yaw_goal_tolerance: 0.05

    # Forward Simulation Parameters
    sim_time: 4.0
    sim_granularity: 0.025
    vx_samples: 10
    vtheta_samples: 20

    # Trajectory Scoring Parameters
    goal_distance_bias: 0.8
    path_distance_bias: 0.8
    occdist_scale: 0.01
    heading_lookahead: 0.325
    dwa: true

    # Oscillation Prevention Parameters
    oscillation_reset_dist: 0.05

