<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <property name="M_PI" value="3.14159"/>
    
    <property name="wheel_radius" value="0.0625" />
    <property name="wheel_length" value="0.02" />
    <property name="caster_wheel_offset_y" value="0.17" />
    
    <property name="wheel_offset_z" value="${-base_size_z/2 + 0.0236}" />    
    
    <macro name="erratic_wheel" params="suffix parent reflect">
        <joint name="${parent}_${suffix}_motor_joint" type="fixed">
            <origin xyz="0.075 ${reflect*base_size_y/2} ${wheel_offset_z}" rpy="0 0 0" />
            <parent link="${parent}" />
            <child link="${parent}_${suffix}_motor_link" />
        </joint>
        
        <link name="${parent}_${suffix}_motor_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz=" 0 ${reflect*0.0125} 0 " />
                <inertia  ixx="0.012411765597" ixy="0.0" ixz="0.0"
                          iyy="0.015218160428" iyz="0.0"
                          izz="0.011763977943" />
            </inertial>
            
            <visual>
                <origin xyz="0 ${reflect*0.0125} 0" rpy="${M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="0.0127" length="0.025" />
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="$0 ${reflect*0.0125} 0" rpy="{M_PI/2} 0 0" />
                <geometry>
                    <cylinder radius="0.0127" length="0.025" />
                </geometry>
            </collision>
        </link>

        <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
            <origin xyz="0 ${reflect*0.025} 0" rpy="0 0 0" />
            <axis xyz="0 1 0" />
            <anchor xyz="0 0 0" />
            <limit effort="100" velocity="100" />
            <joint_properties damping="0.0" friction="0.0" />
            <parent link="${parent}_${suffix}_motor_link" />
            <child link="${parent}_${suffix}_wheel_link" />
        </joint>
        
        <link name="${parent}_${suffix}_wheel_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz=" 0 0 0 " />
                <inertia  ixx="0.012411765597" ixy="0.0" ixz="0.0"
                          iyy="0.015218160428" iyz="0.0"
                          izz="0.011763977943" />
            </inertial>
            
            <visual>
                <origin xyz="0 0 0" rpy="0 0 ${M_PI/2}" />
                <geometry>
                    <mesh filename="package://wubble_robots/meshes/erratic_wheel.stl"/>
<!--                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />-->
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0 0 0" rpy="$0 0 ${M_PI/2}" />
                <geometry>
                    <mesh filename="package://wubble_robots/meshes/erratic_wheel.stl"/>
<!--                    <cylinder radius="${wheel_radius}" length="${wheel_length}" />-->
                </geometry>
            </collision>
        </link>

        <gazebo reference="${parent}_${suffix}_wheel_link" >
            <elem key="mu1" value="50.0" />
            <elem key="mu2" value="50.0" />
            <elem key="kp"  value="100000000.0" />
            <elem key="kd"  value="1.0" />
            <material>PR2/Grey</material>
        </gazebo>

        <gazebo reference="${parent}_${suffix}_motor_link" >
            <material>PR2/White</material>
        </gazebo>
    </macro>
</robot>

