<?xml version="1.0"?>

<robot name="erratic"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <include filename="$(find pr2_defs)/calibration/default_cal.xml" />
    <include filename="$(find wubble_robots)/defs/erratic/head_sensor_package_defs.urdf.xacro" />
    <include filename="$(find pr2_defs)/defs/materials.urdf.xacro" />    
    <include filename="$(find wubble_robots)/defs/erratic/erratic_head.xacro" />
    <include filename="$(find wubble_robots)/defs/erratic/erratic_wheel.xacro" />
    <include filename="$(find wubble_robots)/defs/erratic/erratic_arm.xacro" />

    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    
    <property name="base_size_x" value="0.22" />
    <property name="base_size_y" value="0.29" />
    <property name="base_size_z" value="0.135448" /> <!-- 0.14 -->
    
    <property name="top_size_x" value="0.3937" />
    <property name="top_size_y" value="0.3556" />
    <property name="top_size_z" value="0.0020" />
    
    <property name="wheel_radius" value="0.0625" />
    <property name="wheel_length" value="0.02" />
    <property name="caster_wheel_offset_y" value="0.17" />
    
    <property name="caster_support_x" value="0.086" />
    <property name="caster_support_z" value="0.088148" />
    
    <property name="support_radius" value="0.01" />
    <property name="support_height" value="0.8128" />

    <!-- base_footprint is a fictitious link(frame) that is on the ground right below base_link origin,
         navigation stack dedpends on this frame -->
    <link name="base_footprint">
        <inertial>
            <mass value="1.0" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0" 
                     izz="0.01" />
        </inertial>

        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="0.01 0.01 0.01" />
            </geometry>
            <material name="Green" />
        </visual>

        <collision>
            <!-- represent base collision with a simple rectangular model, positioned by base_size_z s.t. top
                 surface of the collision box matches the top surface of the PR2 base -->
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
              <box size="0.001 0.001 0.001" />
            </geometry>
        </collision>
    </link>

    <joint name="base_footprint_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />        
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>

    <!-- Links and Joints (i.e., the robot) -->
    <link name="base_link">
        <inertial>
            <mass value="20" />
            <origin xyz="${-base_size_x/2} 0 ${-base_size_z/2}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0" 
                     izz="1.0" />
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
            </geometry>
            <material name="Blue" />
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="${base_size_x} ${base_size_y} ${base_size_z}" />
            </geometry>
        </collision>
    </link>

    <joint name="base_top_joint" type="fixed" >
        <origin xyz="0 0 ${base_size_z/2 + top_size_z/2}" rpy="0 0 0" />   <!-- 0.051 -->
        <parent link="base_link" />
        <child link="base_top_link"/>
    </joint>

    <link name="base_top_link">
        <inertial>
            <mass value="1.0"/>
            <origin xyz="-0.00125736 0.0 -0.0032368" />
            <inertia ixx="0.00995424" ixy="0.0" ixz="0.00000413"
                     iyy="0.01191941" iyz="0.0" izx="0.00000413"
                     izz="0.02181097" />
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://wubble_robots/meshes/erratic_top_origin.stl"/>
            </geometry>
            <material name="Blue" />
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://wubble_robots/meshes/erratic_top_origin.stl"/>
            </geometry>
        </collision>
    </link>

    <joint name="base_caster_box_joint" type="fixed">
        <origin xyz="-${base_size_x/2 + caster_support_x/2} 0 ${base_size_z/2 - caster_support_z/2}" rpy="0 0 0" />
        <parent link="base_link" />
        <child link="base_caster_box_link"/>
    </joint>

    <link name="base_caster_box_link">
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01" />
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="${caster_support_x} 0.02 ${caster_support_z}" />
            </geometry>
            <material name="Blue" />
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="${caster_support_x} 0.02 ${caster_support_z}" />
            </geometry>
        </collision>
    </link>

    <joint name="base_caster_support_joint" type="continuous">
        <origin xyz="${-caster_support_x/2 + 0.015} 0 ${-caster_support_z/2 - 0.03}" rpy="0 0 0" />
        <parent link="base_caster_box_link" />
        <child link="base_caster_support_link"/>
        
        <axis xyz="0 0 1" />
        <anchor xyz="0.01 0 0" />
        <limit effort="100" velocity="100" k_velocity="0" />
        <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <transmission type="SimpleTransmission" name="base_caster_support_trans">
        <actuator name="base_caster_support_motor" />
        <joint name="base_caster_support_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>

    <link name="base_caster_support_link">
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" />
            <inertia ixx="0.01" ixy="0.0" ixz="0.0"
                     iyy="0.01" iyz="0.0"
                     izz="0.01" />
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.02 0.06" />
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <box size="0.03 0.02 0.06" />
            </geometry>
        </collision>
    </link>

    <joint name="caster_wheel_joint" type="continuous">
        <origin xyz="-0.015 0 -0.03" rpy="0 0 0" />
        <parent link="base_caster_support_link" />
        <child link="caster_wheel_link" />      
        
        <axis xyz="0 1 0" />
        <anchor xyz="0 0 0" />
        <limit effort="100" velocity="100" k_velocity="0" />
        <joint_properties damping="0.0" friction="0.0" />
    </joint>

    <transmission type="SimpleTransmission" name="caster_wheel_trans">
        <actuator name="caster_wheel_motor" />
        <joint name="caster_wheel_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>

    <link name="caster_wheel_link">
        <inertial>
            <mass value="0.1" /> 
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                      iyy="0.015218160428" iyz="-0.000004273467"
                      izz="0.011763977943" />
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
            <geometry>
                <cylinder radius="0.0381" length="0.01" />
            </geometry>
            <material name="Black"/>
        </visual>
        
        <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
            <cylinder radius="0.0381" length="0.01" />
        </geometry>
        </collision>
    </link>

    <gazebo reference="caster_wheel_link">
        <elem key="mu1" value="50.0" />
        <elem key="mu2" value="50.0" />
        <elem key="kp"  value="100000000.0" />
        <elem key="kd"  value="1.0" />
    </gazebo>

    <joint name="head_support_joint" type="fixed">
        <origin xyz="0.0254 0 ${support_height/2 + top_size_z/2}" />
        <parent link="base_top_link" />
        <child link="head_support_link" />
    </joint>

    <link name="head_support_link"> 
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="head_pan_joint" type="revolute">
        <origin xyz="0 0 ${support_height/2}" />
        <parent link="head_support_link" />
        <child link="head_pan_link" />
        
        <axis xyz="0 0 1" />
<!--        <anchor xyz="0 0 0" />-->
<!--        <limit effort="100" velocity="100" />-->
        <limit lower="0" upper="0" effort="100" velocity="1.0" />
        <dynamics damping="1" friction="1" />
<!--        <safety_controller k_position="100" k_velocity="0.05" soft_lower_limit="${-0.785+0.0}" soft_upper_limit="${1.57-0.0}" />-->
    </joint>

    <transmission type="SimpleTransmission" name="head_pan_trans">
        <actuator name="head_pan_motor" />
        <joint name="head_pan_joint" />
        <mechanicalReduction>6.0</mechanicalReduction>
    </transmission>

    <link name="head_pan_link"> 
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0.0127" rpy="0 0 0"/>
            <geometry>
                <box size="${2*support_radius} ${2*support_radius} 0.0254" />
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0.0127" rpy="0 0 0"/>
            <geometry>
                <box size="${2*support_radius} ${2*support_radius} 0.0254" />
            </geometry>
        </collision>
    </link>

    <!-- MACRO INSTANTIATION -->

    <erratic_wheel suffix="left" parent="base_link" reflect="1"/>
    <erratic_wheel suffix="right" parent="base_link" reflect="-1"/>

    <pr2_tilting_laser name="laser_tilt" parent="base_top_link" laser_calib_ref="-0.35">
        <origin xyz="0.15 0 ${-top_size_z - 0.05}" rpy="0 -1 0" />
    </pr2_tilting_laser>

    <stoc_camera name="stoc" parent="head_pan_link" />

    <arm parent="base_top_link" />


    <!-- CONTROLLERS -->

    <gazebo>
        <controller:differential_position2d name="controller1">
            <update>100</update>
            <leftJoint>base_link_right_wheel_joint</leftJoint>
            <rightJoint>base_link_left_wheel_joint</rightJoint>
            <wheelSeparation>${caster_wheel_offset_y*2}</wheelSeparation>
            <wheelDiameter>${wheel_radius*2}</wheelDiameter>
            <torque>5</torque>
            <interface:position name="position_iface_0"/>
        </controller:differential_position2d>

        <controller:gazebo_ros_p3d name="p3d_base_controller" plugin="libgazebo_ros_p3d.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <bodyName>base_link</bodyName>
            <topicName>base_pose_ground_truth</topicName>
            <gaussianNoise>0.01</gaussianNoise>
            <frameName>map</frameName>
            <xyzOffsets>0 0 0</xyzOffsets> <!-- initialize odometry for fake localization-->
            <rpyOffsets>0 0 0</rpyOffsets>
            <interface:position name="p3d_base_position"/>
        </controller:gazebo_ros_p3d>

        <canonicalBody>base_footprint</canonicalBody>

        <!-- this publishes empty joint_states due to no transmission, but
         triggering robot_state_publisher to publish tf between fixed joints in erratic,
         (e.g. base_laser_link for the base_scan frame) -->
        <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <interface:audio name="gazebo_ros_controller_manager_dummy_iface" />
        </controller:gazebo_ros_controller_manager>
    </gazebo>

    <!-- GAZEBO MATERIALS -->

    <material name="Black">
        <color rgba="0.0 0.0 0.0 1.0"/>
    </material>


    <gazebo reference="base_link">
        <material>Wubble/BlueBrushedAluminum</material>
    </gazebo>

    <gazebo reference="base_top_link">
        <material>Wubble/BlueBrushedAluminum</material>
    </gazebo>

    <gazebo reference="caster_wheel_link">
        <material>PR2/Black</material>
    </gazebo>

    <gazebo reference="base_laser_link">
        <material>PR2/Red</material>
    </gazebo>

    <gazebo reference="base_caster_box_link">
        <material>PR2/Black</material>
    </gazebo>

    <gazebo reference="base_caster_support_link">
        <material>PR2/White</material>
    </gazebo>

    <gazebo reference="head_support_link">
        <material>Wubble/BrassShiny</material>
    </gazebo>

    <gazebo reference="head_pan_link">
        <material>PR2/Black</material>
    </gazebo>

</robot>
