<?xml version="1.0"?>

<robot
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <macro name="arm" params="parent">
        <joint name="arm_base_joint" type="fixed">
            <origin xyz="${top_size_x/2 - 0.0575} 0 ${top_size_z/2 + 0.025}"/>
            <parent link="${parent}"/>
            <child link="arm_base_link"/>
        </joint>
        
        <link name="arm_base_link">
            <inertial>
                <mass value="0.1" />
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
<!--                    <box size="${0.0575*2} ${0.0575*2} ${0.025*2}" />-->
                    <mesh filename="package://wubble_robots/meshes/arm_base.stl"/>
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <box size="${0.0575*2} ${0.0575*2} ${0.025*2}" />
                </geometry>
            </collision>
        </link>
        
        <joint name="arm_base_shoulder_joint" type="revolute" >
            <origin xyz="-0.0075 0 0.025" rpy="0 0 0" />
            <parent link="arm_base_link" />
            <child link="arm_shoulder_pan_link"/>

            <axis xyz="0 0 1"/>
            <limit  lower="-1.22"
                    upper="1.22"
                    effort="100"
                    velocity="2.33" />
        </joint>
        
        <transmission type="SimpleTransmission" name="arm_base_shoulder_trans">
            <actuator name="arm_base_shoulder_motor" />
            <joint name="arm_base_shoulder_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        
        <link name="arm_shoulder_pan_link">
            <inertial>
                <mass value="0.3" />
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.005" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://wubble_robots/meshes/arm_shoulder.stl"/>
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://wubble_robots/meshes/arm_shoulder.stl"/>
                </geometry>
            </collision>
        </link>
        
        <joint name="arm_shoulder_pan_tilt_joint" type="revolute">
            <origin xyz="0.08995 0 0.0450" rpy="0 0 0" />
            <parent link="arm_shoulder_pan_link"/>
            <child link="arm_shoulder_tilt_link" />
            
            <axis xyz="0 1 0"/>
            <limit  lower="-1.972222"
                    upper="1.04719755"
                    effort="100"
                    velocity="2.33" />
        </joint>
        
        <link name="arm_shoulder_tilt_link">
            <inertial>
                <mass value="0.18" />
                <origin xyz="0.0 0.017 0.0" rpy="0 0 0" />
                <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                         iyy="1.0" iyz="0.0" 
                         izz="1.0" />
            </inertial>
            
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://wubble_robots/meshes/arm_shoulder_tilt.stl"/>
                </geometry>
            </visual>
            
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <geometry>
                    <mesh filename="package://wubble_robots/meshes/arm_shoulder_tilt.stl"/>
                </geometry>
            </collision>
        </link>
        
        <transmission type="SimpleTransmission" name="arm_base_shoulder_tilt_trans">
            <actuator name="arm_base_shoulder_tilt_motor" />
            <joint name="arm_shoulder_pan_tilt_joint" />
            <mechanicalReduction>1.0</mechanicalReduction>
        </transmission>
        
        
        <gazebo reference="arm_base_link">
            <material>Wubble/GunMetalBrushedAluminum</material>
        </gazebo>
        
        <gazebo reference="arm_shoulder_pan_link">
            <material>Wubble/GunMetalBrushedAluminum</material>
        </gazebo>
        
        <gazebo reference="arm_shoulder_tilt_link">
            <material>Wubble/GunMetalBrushedAluminum</material>
        </gazebo>
    </macro>
</robot>
