<?xml version="1.0"?>

<robot name="erratic"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <!-- Include file with calibration parameters -->
    <include filename="$(find pr2_defs)/calibration/default_cal.xml" />
<!--    <include filename="$(find pr2_defs)/defs/head/head_defs.urdf.xacro" />-->
    <include filename="$(find pr2_defs)/defs/head/head_sensor_package_defs.urdf.xacro" />
    <include filename="$(find pr2_defs)/defs/materials.urdf.xacro" />    
    <include filename="$(find wubble_robots)/defs/erratic/erratic_head.xacro" />

    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>

    <property name="base_size_x" value="0.395224" />
    <property name="base_size_y" value="0.367284" />
    <property name="base_size_z" value="0.155448" />

    <property name="wheel_radius" value="0.0625" />
    <property name="wheel_length" value="0.02" />
    <property name="caster_wheel_offset_y" value="0.17" />

    <!-- Links and Joints (i.e., the robot) -->
    <link name="base_link">
        <inertial>
            <mass value="10" />
            <origin xyz="-0.1 0 ${base_size_z/2}" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                iyy="1.0" iyz="0.0"
                izz="1.0" />
        </inertial>

        <visual>
            <origin xyz="-0.075 0 0.115" rpy="0 0 0" />
            <geometry>
                <box size="0.22 0.29 0.14" />
            </geometry>
        </visual>

        <collision>
            <origin xyz="-0.075 0 0.115" rpy="0 0 0" />
            <geometry>
                <box size="0.22 0.29 0.14" />
            </geometry>
        </collision>
    </link>


  <joint name="base_top_joint" type="fixed" >
    <origin xyz="0 0 0.051" rpy="0 0 0" />   <!-- 0.051 -->
    <parent link="base_link" />
    <child link="base_top_link"/>
  </joint>

  <link name="base_top_link">
    <inertial>
      <mass value="1.0"/>
      <origin xyz="0 0 ${base_size_z/2}" />
      <inertia ixx="0.0652232699207" ixy="0.0" ixz="0.0"
               iyy="0.0669473158652" iyz="0.0"
               izz="0.0683196351726" />
    </inertial>

    <visual>
        <origin xyz="-0.08 0 0.13" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://wubble_robots/meshes/erratic_top_final.stl"/>
<!--            <mesh filename="package://wubble_robots/meshes/erratic_top.stl"-->
<!--                  scale="${base_size_x/2.0} ${base_size_y/2.0} 0.05">-->
<!--            </mesh>-->
        </geometry>
<!--      <geometry>-->
<!--        <box size="${base_size_x} ${base_size_y} 0.01" />-->
<!--      </geometry>-->
    </visual>
    
    <collision>
        <origin xyz="-0.08 0 0.13" rpy="0 0 0" />
        <geometry>
            <mesh filename="package://wubble_robots/meshes/erratic_top_final.stl"/>
<!--            <mesh filename="package://wubble_robots/meshes/erratic_top.stl"-->
<!--                  scale="${base_size_x/2.0} ${base_size_y/2.0} 0.05">-->
<!--            </mesh>-->
        </geometry>
<!--      <geometry>-->
<!--        <box size="${base_size_x} ${base_size_y} 0.01" />-->
<!--      </geometry>-->
    </collision>
  </link>
  
  <macro name="erratic_wheel" params="suffix parent reflect">
    <joint name="${parent}_${suffix}_wheel_joint" type="continuous">
      <origin xyz="0 ${reflect*caster_wheel_offset_y} ${wheel_radius}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <anchor xyz="0 0 0" />
      <limit effort="100" velocity="100" />
      <joint_properties damping="0.0" friction="0.0" />
      <parent link="${parent}" />
      <child link="${parent}_${suffix}_wheel_link" />
    </joint>
    
    <link name="${parent}_${suffix}_wheel_link">
      <inertial>
        <mass value="0.1" /> <!-- check jmh 20081205 -->
        <origin xyz=" 0 0 0 " />
        <inertia  ixx="0.012411765597" ixy="0.0" ixz="0.0"
                  iyy="0.015218160428" iyz="0.0"
                  izz="0.011763977943" />
      </inertial>
      <visual>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
	
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
        <geometry>
          <cylinder radius="${wheel_radius}" length="${wheel_length}" />
        </geometry>
      </collision>
    </link>

    <gazebo reference="${parent}_${suffix}_wheel_link" >
      <elem key="mu1" value="50.0" />
      <elem key="mu2" value="50.0" />
      <elem key="kp"  value="100000000.0" />
      <elem key="kd"  value="1.0" />
      <material>Gazebo/Black</material> <!-- Had to add this here because it's a macro -->
    </gazebo>
  </macro>

  <erratic_wheel suffix="left" parent="base_link" reflect="1"/>
  <erratic_wheel suffix="right" parent="base_link" reflect="-1"/>
  
  <joint name="base_caster_box_joint" type="fixed">
    <origin xyz="0 0 0.051" rpy="0 0 0" />
    <parent link="base_link" />
    <child link="base_caster_box_link"/>
  </joint>
    
  <link name="base_caster_box_link">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 ${base_size_z/2}" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
    </inertial>

    <visual>
      <origin xyz="-0.23 0 0.08" rpy="0 0 0" />
      <geometry>
        <box size="0.09 0.02 0.10" />
      </geometry>
    </visual>
    
    <collision>
      <origin xyz="-0.23 0 0.08" rpy="0 0 0" />
      <geometry>
        <box size="0.09 0.02 0.10" />
      </geometry>
    </collision>
  </link>
  
  <joint name="base_caster_support_joint" type="continuous">
    <axis xyz="0 0 1" />
    <anchor xyz="0.01 0 0" />
    <limit effort="100" velocity="100" k_velocity="0" />
    <joint_properties damping="0.0" friction="0.0" />
    <parent link="base_caster_box_link" />
    <origin xyz="-0.265 0 0.0" rpy="0 0 0" />
    <child link="base_caster_support_link"/>
  </joint>
  <link name="base_caster_support_link">
    <inertial>
      <mass value="0.1"/>
      <origin xyz="0 0 0" />
      <inertia ixx="0.01" ixy="0.0" ixz="0.0"
               iyy="0.01" iyz="0.0"
               izz="0.01" />
    </inertial>

    <visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.03 0.02 0.06" />
      </geometry>
    </visual>
    
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <box size="0.03 0.02 0.06" />
      </geometry>
    </collision>
  </link>

  <joint name="caster_wheel_joint" type="continuous">
    <origin xyz="-0.02 0 -0.02" rpy="0 0 0" />
    <axis xyz="0 1 0" />
    <anchor xyz="0 0 0" />
    <limit effort="100" velocity="100" k_velocity="0" />
    <joint_properties damping="0.0" friction="0.0" />
    <parent link="base_caster_support_link" />
    <child link="caster_wheel_link" />
  </joint>
  
  <link name="caster_wheel_link">
    <inertial>
      <mass value="0.1" /> 
      <origin xyz=" 0 0 0 " />
      <inertia  ixx="0.012411765597" ixy="-0.000711733678" ixz="0.00050272983"
                iyy="0.015218160428" iyz="-0.000004273467" izz="0.011763977943" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.01" />
      </geometry>
      
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
      <geometry>
        <cylinder radius="0.03" length="0.01" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="caster_wheel_link">
    <elem key="mu1" value="50.0" />
    <elem key="mu2" value="50.0" />
    <elem key="kp"  value="100000000.0" />
    <elem key="kd"  value="1.0" />
  </gazebo>

    <property name="support_radius" value="0.01" />
    <property name="support_height" value="0.3" />

    <joint name="laser_support_joint" type="fixed">
        <origin xyz="0 0 ${(support_height/2)+base_size_z}" />
        <parent link="base_top_link" />
        <child link="laser_support_link" />
    </joint>

    <link name="laser_support_link"> 
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0.0"/>
            <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>
        </inertial>

        <visual>
            <origin rpy="0 0 ${support_height/2}" xyz="0 0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </visual>

        <collision>
            <origin rpy="0 0 ${support_height/2}" xyz="0 0 0.0"/>
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </collision>
    </link>


<!--  <joint name="base_laser_joint" type="fixed">-->
<!--    <origin xyz="0.0 0 ${support_height/2}" rpy="0 0 0" />-->
<!--    <parent link="laser_support_link"/>-->
<!--    <child link="base_laser_link"/>-->
<!--  </joint>-->

<!--  <link name="base_laser_link" type="laser">-->
<!--    <inertial>-->
<!--      <mass value="0.1"/>-->
<!--      <origin xyz="0 0 0.0"/>-->
<!--      <inertia ixx="0.1" ixy="0" ixz="0" iyy="0.1" iyz="0" izz="0.1"/>-->
<!--    </inertial>-->
<!--    -->
<!--    <visual>-->
<!--      <origin rpy="0 0 0" xyz="0 0 0.0"/>-->
<!--      <geometry>-->
<!--        <cylinder radius=".05" length=".05"/>-->
<!--      </geometry>-->
<!--    </visual>-->
<!--    -->
<!--    <collision>-->
<!--      <origin rpy="0 0 0" xyz="0 0 0.0"/>-->
<!--      <geometry>-->
<!--        <cylinder radius=".05" length=".05"/>-->
<!--      </geometry>-->
<!--    </collision>-->
<!--    -->
<!--  </link>-->

<!--  <gazebo reference="base_laser_link">-->
<!--    <sensor:ray name="base_laser_link">-->
<!--      <resRange>0.1</resRange>-->
<!--      <rayCount>640</rayCount>-->
<!--      <rangeCount>640</rangeCount>-->
<!--      <laserCount>1</laserCount>-->
<!--      <origin>0.0 0.0 0.0</origin>-->
<!--      <displayRays>false</displayRays>-->
<!--      -->
<!--      <minAngle>-100</minAngle> -->
<!--      <maxAngle>100</maxAngle>-->
<!--      -->
<!--      <minRange>0.07</minRange>-->
<!--      <maxRange>10.0</maxRange>-->
<!--      <updateRate>20.0</updateRate>-->
<!--      <controller:gazebo_ros_laser name="gazebo_ros_base_laser_link_controller" plugin="libgazebo_ros_laser.so">-->
<!--        <gaussianNoise>0.005</gaussianNoise>-->
<!--        <alwaysOn>true</alwaysOn>-->
<!--        <updateRate>20.0</updateRate>-->
<!--        <topicName>base_scan</topicName>-->
<!--        <frameName>base_laser_link</frameName>-->
<!--        <interface:laser name="gazebo_ros_base_laser_link_iface"/>-->
<!--      </controller:gazebo_ros_laser>-->
<!--    </sensor:ray>-->
<!--  </gazebo>-->

  <gazebo>
    <controller:differential_position2d name="controller1">
      <update>100</update>
      <leftJoint>base_link_right_wheel_joint</leftJoint>
      <rightJoint>base_link_left_wheel_joint</rightJoint>
      <wheelSeparation>${caster_wheel_offset_y*2}</wheelSeparation>
      <wheelDiameter>${wheel_radius*2}</wheelDiameter>
      <torque>5</torque>
      <interface:position name="position_iface_0"/>
    </controller:differential_position2d>
  
    <controller:gazebo_ros_p3d name="p3d_base_controller" plugin="libgazebo_ros_p3d.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>100.0</updateRate>
      <bodyName>base_link</bodyName>
      <topicName>base_pose_ground_truth</topicName>
      <gaussianNoise>0.01</gaussianNoise>
      <frameName>map</frameName>
      <xyzOffsets>25.7 25.7 0</xyzOffsets> <!-- initialize odometry for fake localization-->
      <rpyOffsets>0 0 0</rpyOffsets>
      <interface:position name="p3d_base_position"/>
    </controller:gazebo_ros_p3d>

    <!-- this publishes empty joint_states due to no transmission, but
         triggering robot_state_puublisher to publish tf between fixed joints in erratic,
         (e.g. base_laser_link for the base_scan frame) -->
    <controller:gazebo_ros_controller_manager name="gazebo_ros_controller_manager" plugin="libgazebo_ros_controller_manager.so">
      <alwaysOn>true</alwaysOn>
      <updateRate>1000.0</updateRate>
      <interface:audio name="gazebo_ros_controller_manager_dummy_iface" />
    </controller:gazebo_ros_controller_manager>
  </gazebo>

    <!-- PR2-derived things. These will need to be adapted further to match what we have -->
<!--    <pr2_head name="head" parent="base_top_link">-->
<!--    <origin xyz="${cal_head_x}    ${cal_head_y}     ${0.3915+cal_head_z}"-->
<!--            rpy="${cal_head_roll} ${cal_head_pitch} ${cal_head_yaw}" />-->
<!--    </pr2_head>-->

    <!-- Camera package: double stereo, prosilica -->
<!--    <pr2_head_sensor_package name="sensor_mount" hd_name="high_def" -->
<!--		       stereo_name="double_stereo" -->
<!--		       parent="head_plate_frame">-->
<!--    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />-->
<!--    </pr2_head_sensor_package>-->

    <!-- attempt to add the pan-tilt laser from the pr2, it should be close enough -->
    <pr2_tilting_laser name="laser_tilt" parent="base_top_link" laser_calib_ref="-0.35">
        <origin xyz="0.1 0 0.235" rpy="0 0 0" />
    </pr2_tilting_laser>

    <stoc_camera name="stoc" parent="base_top_link" />

    <!-- Gazebo materials -->
    <gazebo reference="base_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="base_top_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="caster_wheel_link">
        <material>Gazebo/Black</material>
    </gazebo>
    <gazebo reference="base_laser_link">
        <material>Gazebo/Red</material>
    </gazebo>
    <gazebo reference="base_caster_box_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="base_caster_support_link">
        <material>Gazebo/Blue</material>
    </gazebo>
    <gazebo reference="laser_support_link">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>
