VerbInstance verb
oomdp_msgs/MDPState start_state # get this from calling initialize
int32 execution_limit  # max number of steps in execution before failure
---
oomdp_msgs/MDPState[] trace
string[] actions
int64 planning_time
int32 execution_length # is this just the length of the trace?
bool execution_success
