---
sensor_msgs/Image average_background    # mean image composed from n samples
float32[] covariance_matrix             # 3x3 covariance matrix array for each pixel in the image
float32[] covariance_matrix_inv         # inverse of covariance matrices
float32[] covariance_matrix_dets        # covariance matrix determinant array for each pixel
float32[] standard_deviations           # standard deviation array for each component of a pixel (bgr)

