/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewJFrame.java
 *
 * Created on Nov 15, 2010, 6:48:51 PM
 */

package edu.arizona.teach;

import java.io.File;

/**
 *
 * @author diana
 */
public class BuildVerb extends javax.swing.JFrame {
    MainWindow myView;
    String myVerb;
    String myScenario;

    /** Creates new form NewJFrame */
    public BuildVerb(MainWindow thisView) {
        myView = thisView;
        myVerb = thisView.getVerbName();
        myScenario = thisView.getScenarioName();
        initComponents();
        buildVerbTable(myVerb, jTable3);
        buildScenarioTable(myScenario, jTable2);

    }

     public BuildVerb() {

        initComponents();
        myVerb = "";
        myScenario = "";

    }

    /* fill verb table with your verb parameters */
    public void buildVerbTable(String thisVerb, javax.swing.JTable thisTable) {
        System.out.println("myverb is " + thisVerb);
        File verbFile = new File("__wubble_verbs__", thisVerb);
        File[] paramArray = verbFile.listFiles();

        String[][] myParams = new String[paramArray.length][1];

        for (int i = 0; i < paramArray.length; i++) {
            myParams[i][0] = paramArray[i].toString();
        }


        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            myParams,
            new String [] {
        "parameter", "name"
    }
));

    }

    /* fill scenario table with your scenario components */
    public void buildScenarioTable(String thisScenario, javax.swing.JTable thisTable) {
        File scenarioFile = new File("__wubble_scenarios__", thisScenario);
        File[] itemArray = scenarioFile.listFiles();
        String[][] myItems = new String[itemArray.length][1];
        for (int i = 0; i < itemArray.length; i++) {
            myItems[i][0] = itemArray[i].toString();
        }

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            myItems,
            new String [] {
        "type", "name"
    }
));
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setName("Form"); // NOI18N
        getContentPane().setLayout(null);

        jPanel4.setName("jPanel4"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(edu.arizona.teach.WubbleTeach.class).getContext().getResourceMap(BuildVerb.class);
        jLabel3.setFont(resourceMap.getFont("jLabel3.font")); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText(resourceMap.getString("jLabel3.text")); // NOI18N
        jLabel3.setName("jLabel3"); // NOI18N

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 338, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 35, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4);
        jPanel4.setBounds(0, 0, 350, 50);

        jScrollPane2.setName("jScrollPane2"); // NOI18N

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"agent", "self"},
                {"goal", "tree"},
                {"obstacle", "<select item>"},
                {null, null},
                {null, null}
            },
            new String [] {
                "parameter", "Title 2"
            }
        ));
        jTable2.setCellSelectionEnabled(true);
        jTable2.setDragEnabled(true);
        jTable2.setDropMode(javax.swing.DropMode.INSERT);
        jTable2.setName("jTable2"); // NOI18N
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(200, 100, 190, 180);

        jButton3.setForeground(resourceMap.getColor("jButton3.foreground")); // NOI18N
        jButton3.setText(resourceMap.getString("jButton3.text")); // NOI18N
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.setName("jButton3"); // NOI18N
        getContentPane().add(jButton3);
        jButton3.setBounds(200, 450, 140, 30);

        jLabel1.setText(resourceMap.getString("jLabel1.text")); // NOI18N
        jLabel1.setName("jLabel1"); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 70, 320, 20);

        jLabel5.setText(resourceMap.getString("jLabel5.text")); // NOI18N
        jLabel5.setName("jLabel5"); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 50, 320, 30);

        jButton5.setForeground(resourceMap.getColor("jButton5.foreground")); // NOI18N
        jButton5.setText(resourceMap.getString("jButton5.text")); // NOI18N
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setName("jButton5"); // NOI18N
        getContentPane().add(jButton5);
        jButton5.setBounds(20, 450, 70, 30);

        jScrollPane3.setName("jScrollPane3"); // NOI18N

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"agent", "self"},
                {"goal", "tree"},
                {"obstacle", "<select item>"},
                {null, null},
                {null, null}
            },
            new String [] {
                "parameter", "Title 2"
            }
        ));
        jTable3.setCellSelectionEnabled(true);
        jTable3.setDragEnabled(true);
        jTable3.setDropMode(javax.swing.DropMode.INSERT);
        jTable3.setName("jTable3"); // NOI18N
        jScrollPane3.setViewportView(jTable3);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(20, 100, 170, 180);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuildVerb().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables

}
