/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/oomdp_msgs/srv/DescribeMDP.srv.  Do not edit! */
package ros.pkg.oomdp_msgs.srv;

import java.nio.ByteBuffer;

public class DescribeMDP extends ros.communication.Service<DescribeMDP.Request, DescribeMDP.Response> 
{

public static String __s_getDataType() { return "oomdp_msgs/DescribeMDP"; }
public static String __s_getMD5Sum() { return "2224532b29198ea2142278f3a904b064"; }

public String getDataType() { return DescribeMDP.__s_getDataType(); }
public String getMD5Sum() { return DescribeMDP.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{


  public Request() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "oomdp_msgs/DescribeMDPRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("2224532b29198ea2142278f3a904b064"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("oomdp_msgs/DescribeMDP"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
  }
  public void deserialize(ByteBuffer bb)  {
  }
}

public static class Response extends ros.communication.Message
{

  public ros.pkg.oomdp_msgs.msg.MDPDescription description;

  public Response() {
 super();
    description = new ros.pkg.oomdp_msgs.msg.MDPDescription();

  }
  public static java.lang.String __s_getDataType() { return "oomdp_msgs/DescribeMDPResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "MDPDescription description\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/MDPDescription\n" + 
    "MDPClassDescription[] classes\n" + 
    "string[] actions\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/MDPClassDescription\n" + 
    "string name\n" + 
    "string[] attributes\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("2224532b29198ea2142278f3a904b064"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("oomdp_msgs/DescribeMDP"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
      description = (ros.pkg.oomdp_msgs.msg.MDPDescription)description.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("description", "ros.pkg.oomdp_msgs.msg.MDPDescription");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.oomdp_msgs.msg.MDPDescription");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    description = __m2.description;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += description.serializationLength(); // description
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
     description.serialize(bb, seq);
  }
  public void deserialize(ByteBuffer bb)  {
     description.deserialize(bb);
  }
}

public DescribeMDP.Request createRequest() { return new DescribeMDP.Request(); }public DescribeMDP.Response createResponse() { return new DescribeMDP.Response(); }}

