/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/oomdp_msgs/srv/PerformAction.srv.  Do not edit! */
package ros.pkg.oomdp_msgs.srv;

import java.nio.ByteBuffer;

public class PerformAction extends ros.communication.Service<PerformAction.Request, PerformAction.Response> 
{

public static String __s_getDataType() { return "oomdp_msgs/PerformAction"; }
public static String __s_getMD5Sum() { return "11049c6eac6291be250bffe5ac791779"; }

public String getDataType() { return PerformAction.__s_getDataType(); }
public String getMD5Sum() { return PerformAction.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public java.lang.String action;

  public Request() {
 super();
    action = new java.lang.String();

  }
  public static java.lang.String __s_getDataType() { return "oomdp_msgs/PerformActionRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string action\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("11049c6eac6291be250bffe5ac791779"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("oomdp_msgs/PerformAction"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("action", "java.lang.String");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    action = __m2.action;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + action.length(); // action
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, action);
  }
  public void deserialize(ByteBuffer bb)  {
    action = Serialization.readString(bb);
  }
}

public static class Response extends ros.communication.Message
{

  public ros.pkg.oomdp_msgs.msg.MDPState new_state;

  public Response() {
 super();
    new_state = new ros.pkg.oomdp_msgs.msg.MDPState();

  }
  public static java.lang.String __s_getDataType() { return "oomdp_msgs/PerformActionResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "MDPState new_state\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/MDPState\n" + 
    "MDPObjectState[] object_states\n" + 
    "Relation[] relations\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/MDPObjectState\n" + 
    "string class_name\n" + 
    "string name\n" + 
    "string[] attributes\n" + 
    "string[] values\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/Relation\n" + 
    "string relation\n" + 
    "string[] obj_names\n" + 
    "bool value\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("11049c6eac6291be250bffe5ac791779"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("oomdp_msgs/PerformAction"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
      new_state = (ros.pkg.oomdp_msgs.msg.MDPState)new_state.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("new_state", "ros.pkg.oomdp_msgs.msg.MDPState");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.oomdp_msgs.msg.MDPState");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    new_state = __m2.new_state;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += new_state.serializationLength(); // new_state
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
     new_state.serialize(bb, seq);
  }
  public void deserialize(ByteBuffer bb)  {
     new_state.deserialize(bb);
  }
}

public PerformAction.Request createRequest() { return new PerformAction.Request(); }public PerformAction.Response createResponse() { return new PerformAction.Response(); }}

