/* auto-generated by genmsg_cpp from /home/jeff/ros/ua-ros-pkg/ua_experimental/ultraspeech/msg/AudioStream.msg.  Do not edit! */
package ros.pkg.ultraspeech.msg;


import java.nio.ByteBuffer;

public  class AudioStream extends ros.communication.Message
{

  public ros.pkg.roslib.msg.Header header;
  public int which_channel;
  public float[] samples;
  public int num_channels;
  public int sample_rate;

  public AudioStream() {
 super();
    header = new ros.pkg.roslib.msg.Header();
  samples = new float[0];

  }
  public static java.lang.String __s_getDataType() { return "ultraspeech/AudioStream"; }
  public static java.lang.String __s_getMD5Sum() { return "e75f13067c4581e6d6ac1ce905ecf22c"; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "Header header\n" + 
    "uint32 which_channel\n" + 
    "float32[] samples\n" + 
    "uint32 num_channels\n" + 
    "uint32 sample_rate\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: roslib/Header\n" + 
    "# Standard metadata for higher-level stamped data types.\n" + 
    "# This is generally used to communicate timestamped data \n" + 
    "# in a particular coordinate frame.\n" + 
    "# \n" + 
    "# sequence ID: consecutively increasing ID \n" + 
    "uint32 seq\n" + 
    "#Two-integer timestamp that is expressed as:\n" + 
    "# * stamp.secs: seconds (stamp_secs) since epoch\n" + 
    "# * stamp.nsecs: nanoseconds since stamp_secs\n" + 
    "# time-handling sugar is provided by the client library\n" + 
    "time stamp\n" + 
    "#Frame this data is associated with\n" + 
    "# 0: no frame\n" + 
    "# 1: global frame\n" + 
    "string frame_id\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public AudioStream clone() {
    AudioStream clone = (AudioStream)super.clone();
      header = (ros.pkg.roslib.msg.Header)header.clone();
      samples =  (float[])(clone.samples.clone());
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("header", "ros.pkg.roslib.msg.Header");
     m.put("which_channel", "int");
     m.put("samples", "float[]");
     m.put("num_channels", "int");
     m.put("sample_rate", "int");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.roslib.msg.Header");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof AudioStream)) throw new RuntimeException("Invalid Type");
    AudioStream __m2 = (AudioStream) __m;
    header = __m2.header;
    which_channel = __m2.which_channel;
    samples = __m2.samples;
    num_channels = __m2.num_channels;
    sample_rate = __m2.sample_rate;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += header.serializationLength(); // header
    __l += 4; // which_channel
    __l += 4 + (samples.length == 0 ? 0 : samples.length * (4)); // samples
    __l += 4; // num_channels
    __l += 4; // sample_rate
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    ros.pkg.roslib.msg.Header _ser_header = header;
    boolean __reset_seq = (header.seq == 0);
    if (__reset_seq) _ser_header.seq = seq;
    boolean __reset_timestamp = header.stamp.isZero();
    if (__reset_timestamp)
      _ser_header.stamp = ros.Ros.getInstance().now();
     header.serialize(bb, seq);
    bb.putInt(which_channel);
    bb.putInt(samples.length);
    bb.position(bb.position() + bb.asFloatBuffer().put(samples).position() * 4);
    bb.putInt(num_channels);
    bb.putInt(sample_rate);
  }
  public void deserialize(ByteBuffer bb)  {
     header.deserialize(bb);
    which_channel = bb.getInt();
     int samples_len = bb.getInt();
    samples = new float[samples_len];
    bb.position(bb.position() + bb.asFloatBuffer().get(samples).position() * 4);
    num_channels = bb.getInt();
    sample_rate = bb.getInt();
  }
}

