/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/verb_learning/srv/PlanVerb.srv.  Do not edit! */
package ros.pkg.verb_learning.srv;

import java.nio.ByteBuffer;

public class PlanVerb extends ros.communication.Service<PlanVerb.Request, PlanVerb.Response> 
{

public static String __s_getDataType() { return "verb_learning/PlanVerb"; }
public static String __s_getMD5Sum() { return "af36b15b68baa900ff49e92bd3b713e4"; }

public String getDataType() { return PlanVerb.__s_getDataType(); }
public String getMD5Sum() { return PlanVerb.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public ros.pkg.verb_learning.msg.VerbInstance verb;
  public ros.pkg.oomdp_msgs.msg.MDPState start_state;

  public Request() {
 super();
    verb = new ros.pkg.verb_learning.msg.VerbInstance();
    start_state = new ros.pkg.oomdp_msgs.msg.MDPState();

  }
  public static java.lang.String __s_getDataType() { return "verb_learning/PlanVerbRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "VerbInstance verb\n" + 
    "oomdp_msgs/MDPState start_state\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("af36b15b68baa900ff49e92bd3b713e4"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("verb_learning/PlanVerb"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
      verb = (ros.pkg.verb_learning.msg.VerbInstance)verb.clone();
      start_state = (ros.pkg.oomdp_msgs.msg.MDPState)start_state.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("verb", "ros.pkg.verb_learning.msg.VerbInstance");
     m.put("start_state", "ros.pkg.oomdp_msgs.msg.MDPState");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.verb_learning.msg.VerbInstance");
     s.add("ros.pkg.oomdp_msgs.msg.MDPState");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    verb = __m2.verb;
    start_state = __m2.start_state;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += verb.serializationLength(); // verb
    __l += start_state.serializationLength(); // start_state
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
     verb.serialize(bb, seq);
     start_state.serialize(bb, seq);
  }
  public void deserialize(ByteBuffer bb)  {
     verb.deserialize(bb);
     start_state.deserialize(bb);
  }
}

public static class Response extends ros.communication.Message
{

  public ros.pkg.verb_learning.msg.Policy plan;
  public long time_millis;
  public byte success;

  public Response() {
 super();
    plan = new ros.pkg.verb_learning.msg.Policy();

  }
  public static java.lang.String __s_getDataType() { return "verb_learning/PlanVerbResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "Policy plan\n" + 
    "int64 time_millis\n" + 
    "bool success\n" + 
    "\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: verb_learning/VerbInstance\n" + 
    "string verb\n" + 
    "string[] arguments # These are the role names\n" + 
    "string[] bindings # These are the object names\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/MDPState\n" + 
    "MDPObjectState[] object_states\n" + 
    "Relation[] relations\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/MDPObjectState\n" + 
    "string class_name\n" + 
    "string name\n" + 
    "string[] attributes\n" + 
    "string[] values\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: oomdp_msgs/Relation\n" + 
    "string relation\n" + 
    "string[] obj_names\n" + 
    "bool value\n" + 
    "\n" + 
    "================================================================================\n" + 
    "MSG: verb_learning/Policy\n" + 
    "oomdp_msgs/MDPState[] states\n" + 
    "string[] actions\n" + 
    "string TERMINATE=TERMINATE\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("af36b15b68baa900ff49e92bd3b713e4"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("verb_learning/PlanVerb"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
      plan = (ros.pkg.verb_learning.msg.Policy)plan.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("plan", "ros.pkg.verb_learning.msg.Policy");
     m.put("time_millis", "long");
     m.put("success", "byte");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      s.add("ros.pkg.verb_learning.msg.Policy");
     return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    plan = __m2.plan;
    time_millis = __m2.time_millis;
    success = __m2.success;
    }

  public int serializationLength() 
  {
    int __l = 0;
    __l += plan.serializationLength(); // plan
    __l += 8; // time_millis
    __l += 1; // success
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
     plan.serialize(bb, seq);
    bb.putLong(time_millis);
    bb.put(success);
  }
  public void deserialize(ByteBuffer bb)  {
     plan.deserialize(bb);
    time_millis = bb.getLong();
    success = bb.get();
  }
}

public PlanVerb.Request createRequest() { return new PlanVerb.Request(); }public PlanVerb.Response createResponse() { return new PlanVerb.Response(); }}

