l_arm_controller:
    joint_controllers:
        - shoulder_pitch_controller
        - shoulder_yaw_controller
        - shoulder_roll_controller
        - elbow_pitch_controller
        - wrist_roll_controller
        - wrist_pitch_controller
        - wrist_yaw_controller

    joint_trajectory_action_node:
        joints:
            - shoulder_pitch_joint
            - shoulder_yaw_joint
            - shoulder_roll_joint
            - elbow_pitch_joint
            - wrist_roll_joint
            - wrist_pitch_joint
            - wrist_yaw_joint
        constraints:
            goal_time: 1.0

