l_arm_controller:
    joint_controllers:
        - shoulder_pitch_controller
        - shoulder_pan_controller
        - upperarm_roll_controller
        - elbow_flex_controller
        - forearm_roll_controller
        - wrist_pitch_controller
        - wrist_roll_controller

    joint_trajectory_action_node:
        min_velocity: 0.6
        constraints:
            goal_time: 1.5

