pub_rate: 1.0
base_path: ''
analyzers:
  dynamixel_bus:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Dynamixel Serial Buses'
    timeout: 5.0
    startswith: ['Dynamixel Serial Bus']
  dynamixel_motors:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Dynamixel Motors'
    timeout: 5.0
    startswith: ['Robotis Dynamixel Motor']
  joints:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Joints'
    timeout: 5.0
    startswith: ['Joint Controller']
  power:
    type: GenericAnalyzer
    path: 'Power System'
    timeout: 5.0
    startswith: ['Laptop Battery']

  lasers:
    type: diagnostic_aggregator/AnalyzerGroup
    path: Lasers
    analyzers:
      base_hk:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Base Hokuyo
        find_and_remove_prefix: base_laser
        num_items: 2
      tilt_hk:
        type: diagnostic_aggregator/GenericAnalyzer
        path: Tilt Hokuyo
        find_and_remove_prefix: neck_laser
        num_items: 2

