head_pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_pan_joint
    joint_speed: 1.17
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023

head_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: head_tilt_joint
    joint_speed: 1.17
    motor:
        id: 11
        init: 1690
        min: 600
        max: 3500

neck_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: neck_tilt_joint
    joint_speed: 1.17
    motor:
        id: 14
        init: 355
        min: 300
        max: 900

