left_finger_controller:
    type: dynamixel_hardware_interface/JointTorqueController
    joint: left_finger_joint
    motors:
        - id: 8
          init: 512
          min: 450
          max: 680

right_finger_controller:
    type: dynamixel_hardware_interface/JointTorqueController
    joint: right_finger_joint
    motors:
        - id: 9
          init: 512
          min: 330
          max: 560

l_gripper_controller:
    type: wubble2_gripper_controller/WubbleGripperActionController
    dependencies:
        - left_finger_controller
        - right_finger_controller
    left_controller_name: left_finger_controller
    right_controller_name: right_finger_controller

