pub_rate: 1.0
base_path: ''
analyzers:
  dynamixel_bus:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Dynamixel Serial Buses'
    timeout: 5.0
    startswith: ['Dynamixel Serial Bus']
  dynamixel_motors:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Dynamixel Motors'
    timeout: 5.0
    startswith: ['Robotis Dynamixel Motor']
  joints:
    type: diagnostic_aggregator/GenericAnalyzer
    path: 'Joints'
    timeout: 5.0
    startswith: ['Joint Controller']
