head_pan_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: head_pan_joint
    joint_speed: 1.17
    motor:
        id: 10
        init: 512
        min: 0
        max: 1023

head_tilt_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: head_tilt_joint
    joint_speed: 1.17
    motor:
        id: 11
        init: 1670
        min: 600
        max: 3000

neck_tilt_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: neck_tilt_joint
    joint_speed: 1.17
    motor:
        id: 14
        init: 355
        min: 300
        max: 900

