<?xml version="1.0"?>

<robot name="erratic"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <include filename="$(find erratic_description)/urdf/erratic_base.xacro" />
    <include filename="$(find erratic_description)/urdf/erratic_hokuyo_laser.xacro" />
    
    <erratic />

    <!-- BASE LASER ATTACHMENT -->
    <erratic_hokuyo_laser parent="base_top_link">
        <origin xyz="${top_size_x/2 - 0.01 - 0.04} 0 ${top_size_z/2}" rpy="0 0 0" />
    </erratic_hokuyo_laser>
</robot>
