/* auto-generated by genmsg_cpp from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/oomdp_msgs/msg/MDPObjectState.msg.  Do not edit! */
package ros.pkg.oomdp_msgs.msg;


import java.nio.ByteBuffer;

public  class MDPObjectState extends ros.communication.Message
{

  public java.lang.String class_name;
  public java.lang.String name;
  public java.lang.String[] attributes;
  public java.lang.String[] values;

  public MDPObjectState() {
 super();
    class_name = new java.lang.String();
    name = new java.lang.String();
  attributes = new java.lang.String[0];
  values = new java.lang.String[0];

  }
  public static java.lang.String __s_getDataType() { return "oomdp_msgs/MDPObjectState"; }
  public static java.lang.String __s_getMD5Sum() { return "a7399f0693145f91d4095978930484ce"; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string class_name\n" + 
    "string name\n" + 
    "string[] attributes\n" + 
    "string[] values\n" + 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public MDPObjectState clone() {
    MDPObjectState clone = (MDPObjectState)super.clone();
      attributes =  (java.lang.String[])(clone.attributes.clone());
      values =  (java.lang.String[])(clone.values.clone());
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("class_name", "java.lang.String");
     m.put("name", "java.lang.String");
     m.put("attributes", "java.lang.String[]");
     m.put("values", "java.lang.String[]");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof MDPObjectState)) throw new RuntimeException("Invalid Type");
    MDPObjectState __m2 = (MDPObjectState) __m;
    class_name = __m2.class_name;
    name = __m2.name;
    attributes = __m2.attributes;
    values = __m2.values;
    }

  int calc_attributes_array_serialization_len() {
    int l = 0;
    for (int i = 0; i < attributes.length; i++) 
      l += 4 + attributes[i].length();
    return l;
  }
  int calc_values_array_serialization_len() {
    int l = 0;
    for (int i = 0; i < values.length; i++) 
      l += 4 + values[i].length();
    return l;
  }
  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + class_name.length(); // class_name
    __l += 4 + name.length(); // name
    __l += 4 + calc_attributes_array_serialization_len(); // attributes
    __l += 4 + calc_values_array_serialization_len(); // values
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, class_name);
    Serialization.writeString(bb, name);
    bb.putInt(attributes.length);
    for (java.lang.String x : attributes)
      Serialization.writeString(bb, x);
    bb.putInt(values.length);
    for (java.lang.String x : values)
      Serialization.writeString(bb, x);
  }
  public void deserialize(ByteBuffer bb)  {
    class_name = Serialization.readString(bb);
    name = Serialization.readString(bb);
     int attributes_len = bb.getInt();
    attributes = new java.lang.String[attributes_len];
    for(int i = 0; i < attributes_len; i++)
      attributes[i] = Serialization.readString(bb);
     int values_len = bb.getInt();
    values = new java.lang.String[values_len];
    for(int i = 0; i < values_len; i++)
      values[i] = Serialization.readString(bb);
  }
}

