pan_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: pan_joint
    max_velocity: 3.2
    motor:
        id: 4
        init: 512
        min: 0
        max: 1023

tilt_controller:
    type: dynamixel_hardware_interface/JointPositionController
    joint: tilt_joint
    max_velocity: 3.2
    motor:
        id: 5
        init: 512
        min: 0
        max: 1023

multi_joint_c:
    type: dynamixel_hardware_interface/JointTrajectoryActionController
    dependencies:
        - pan_controller
        - tilt_controller
    joint_trajectory_action_node:
        min_velocity: 0.1
        constraints:
            goal_time: 0.25

wheel_controller:
    type: dynamixel_hardware_interface/JointTorqueController
    joint: wheel_joint
    max_velocity: 3.2
    motor:
        id: 13
        init: 512
        min: 0
        max: 1023


