<?xml version="1.0"?>

<robot name="wubble2"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <!-- Included URDF Files -->
    <include filename="$(find erratic_description)/urdf/erratic_base.xacro" />
    <include filename="$(find hokuyo_urg_description)/urdf/hokuyo_urg.xacro" />
    <include filename="$(find wubble_arm_description)/urdf/wubble_arm.xacro" />
    <include filename="$(find swissranger_camera_description)/urdf/swissranger_camera.xacro" />
    <include filename="$(find videre_stoc_description)/urdf/videre_stereo_6cm.xacro" />
    <include filename="$(find chr_6dm_imu_description)/urdf/chrobotics_chr_6dm_imu.urdf.xacro" />
    
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
    
    <!-- VIDERE ERRATIC MOBILE BASE -->
    <erratic /> 
    
    <!-- WUBBLE PLATFORM ATTACHMENT -->
    <joint name="platform_support_joint" type="fixed">
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_top_link"/>
        <child link="platform_link"/>
    </joint>
    
    <link name="platform_link"> 
        <inertial>
            <mass value="2.165"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.25120" ixy="0" ixz="0"
                     iyy="0.25303" iyz="0"
                     izz="0.02443"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/wubble2_platform.stl"/>
            </geometry>
            <material name="White" />
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/wubble2_platform.dae"/>
            </geometry>
        </collision>
    </link>
    
    <!-- CHR-6dm IMU ATTACHMENT -->
    <chrobotics_chr_6dm_imu name="imu" parent="platform_link" imu_topic="imu/data" update_rate="120.0" stdev="0.00017" >
        <origin xyz="0 0 1.0" rpy="0 0 0" />
    </chrobotics_chr_6dm_imu>
    
    <!-- WUBBLE HEAD ATTACHMENT -->
    <joint name="head_base_joint" type="fixed">
        <origin xyz="0.0264 0 0.7811" rpy="0 0 0" />
        <parent link="platform_link"/>
        <child link="head_base_link"/>
    </joint>
    
    <joint name="head_pan_joint" type="revolute">
        <origin xyz="0.052 0 0.025" rpy="0 0 0" />
        <parent link="head_base_link"/>
        <child link="head_pan_link"/>
        
        <axis xyz="0 0 1" />
        <limit lower="-2.61" upper="2.61" effort="100" velocity="12.0" />
        <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-2.61}" soft_upper_limit="${2.61}" />
        <dynamics damping="50" friction="1"/>
    </joint>
    
    <joint name="head_tilt_joint" type="revolute">
        <origin xyz="0.02899 0 0.03458" rpy="0 0 0" />
        <parent link="head_pan_link"/>
        <child link="head_tilt_link"/>
        
        <axis xyz="0 1 0" />
        <limit lower="-1.57" upper="1.57" effort="100" velocity="12.0" />
        <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.57}" soft_upper_limit="${1.57}" />
        <dynamics damping="50" friction="1"/>
    </joint>
    
    <link name="head_base_link"> 
        <inertial>
            <mass value="0.13"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0" ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/head_base_link.stl"/>
            </geometry>
            <material name="GunMetalBrushedAluminum" />
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/head_base_link.dae"/>
            </geometry>
        </collision>
    </link>
    
    <link name="head_pan_link"> 
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0" ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/head_pan_link.stl"/>
            </geometry>
            <material name="GunMetalBrushedAluminum" />
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/head_pan_link.dae"/>
            </geometry>
        </collision>
    </link>
    
    <link name="head_tilt_link"> 
        <inertial>
            <mass value="0.25"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0" ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/head_tilt_link.stl"/>
            </geometry>
            <material name="GunMetalBrushedAluminum" />
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/head_tilt_link.dae"/>
            </geometry>
        </collision>
    </link>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="head_pan_trans">
        <actuator name="head_pan_motor" />
        <joint name="head_pan_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="head_tilt_trans">
        <actuator name="head_tilt_motor" />
        <joint name="head_tilt_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
    <!-- WUBBLE ARM ATTACHMENT -->
    <wubble_arm parent="base_top_link" >
        <origin xyz="0.16281 0.0825 ${top_size_z/2 + 0.109}" rpy="0 0 0"/>
    </wubble_arm>
    
    <!-- KINECT ATTACHMENT -->
    <joint name="base_kinect_joint" type="fixed">
        <origin xyz="0.04 0 0.08173" rpy="0 0 0" />
        <parent link="head_tilt_link"/>
        <child link="kinect_link"/>
    </joint>
    
    <link name="kinect_link">
        <inertial>
            <mass value="0.00001" />
            <origin xyz="0 0 0" />
            <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                     iyy="1.0" iyz="0.0"
                     izz="1.0" />
        </inertial>
        
        <visual>
            <origin xyz=" 0 0 0 " rpy="0 0 0" />
            <geometry>
                <mesh filename="package://wubble_description/meshes/kinect.stl"/>
            </geometry>
            <material name="Black" />
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/kinect.dae"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="kinect_depth_joint" type="fixed">
        <origin xyz="0 0.018 0" rpy="0 0 0" />
        <parent link="kinect_link" />
        <child link="kinect_depth_frame" />
    </joint>
    
    <link name="kinect_depth_frame">
        <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>
    
    <joint name="kinect_depth_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="kinect_depth_frame" />
        <child link="kinect_depth_optical_frame" />
    </joint>
    
    <link name="kinect_depth_optical_frame">
        <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>
    
    <joint name="kinect_rgb_joint" type="fixed">
        <origin xyz="0 -0.005 0" rpy="0 0 0" />
        <parent link="kinect_link" />
        <child link="kinect_rgb_frame" />
    </joint>
    
    <link name="kinect_rgb_frame">
        <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>
    
    <joint name="kinect_rgb_optical_joint" type="fixed">
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 ${-M_PI/2}" />
        <parent link="kinect_rgb_frame" />
        <child link="kinect_rgb_optical_frame" />
    </joint>
    
    <link name="kinect_rgb_optical_frame">
        <inertial>
            <mass value="0.000001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0001" ixy="0.0" ixz="0.0"
                     iyy="0.0001" iyz="0.0"
                     izz="0.0001" />
        </inertial>
    </link>
    
    <!-- NECK TILTING LASER ATTACHMENT -->
    <joint name="neck_support_joint" type="fixed">
        <origin xyz="0.0254 0 0.655" rpy="0 0 0" />
        <parent link="platform_link"/>
        <child link="neck_support_link"/>
    </joint>
    
    <joint name="neck_tilt_joint" type="revolute">
        <origin xyz="0.0316 0 0" rpy="0 0 0" />
        <parent link="neck_support_link"/>
        <child link="neck_tilt_link"/>
        
        <axis xyz="0 1 0" />
        <limit lower="-1.57" upper="1.57" effort="100" velocity="12.0" />
        <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.57}" soft_upper_limit="${1.57}" />
        <dynamics damping="50" friction="1"/>
    </joint>
    
    <link name="neck_support_link"> 
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0" ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/neck_laser_support_link.stl"/>
            </geometry>
            <material name="GunMetalBrushedAluminum" />
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/neck_laser_support_link.dae"/>
            </geometry>
        </collision>
    </link>
    
    <link name="neck_tilt_link"> 
        <inertial>
            <mass value="0.05"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.1" ixy="0" ixz="0"
                     iyy="0.1" iyz="0"
                     izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/neck_tilt_link.stl"/>
            </geometry>
            <material name="GunMetalBrushedAluminum" />
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/collada/neck_tilt_link.dae"/>
            </geometry>
        </collision>
    </link>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="neck_tilt_trans">
        <actuator name="neck_tilt_motor" />
        <joint name="neck_tilt_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
    <hokuyo_urg name="neck_scan" parent="neck_tilt_link">
        <origin xyz="0.00478 0.00334 0.021" rpy="0 0 0" />
    </hokuyo_urg>
    
    <!-- BASE LASER ATTACHMENT -->
    <hokuyo_urg name="base_scan" parent="base_top_link">
        <origin xyz="${top_size_x/2 - 0.01 - 0.04} 0 -${top_size_z/2}" rpy="${M_PI} 0 0" />
    </hokuyo_urg>
    
    <!-- GAZEBO MATERIALS -->  
    <gazebo reference="head_base_link">
        <material>SmartArm/GunMetalBrushedAluminum</material>
        <turnGravityOff>true</turnGravityOff>
    </gazebo>
    
    <gazebo reference="head_pan_link">
        <material>SmartArm/GunMetalBrushedAluminum</material>
        <turnGravityOff>true</turnGravityOff>
    </gazebo>
    
    <gazebo reference="head_tilt_link">
        <material>SmartArm/GunMetalBrushedAluminum</material>
        <turnGravityOff>true</turnGravityOff>
    </gazebo>
    
    <gazebo reference="neck_support_link">
        <material>SmartArm/GunMetalBrushedAluminum</material>
        <turnGravityOff>true</turnGravityOff>
    </gazebo>
    
    <gazebo reference="neck_tilt_link">
        <material>SmartArm/GunMetalBrushedAluminum</material>
        <turnGravityOff>true</turnGravityOff>
    </gazebo>
    
    <gazebo reference="platform_link">
        <material>Erratic/White</material>
        <turnGravityOff>true</turnGravityOff>
    </gazebo>
</robot>

