<?xml version="1.0"?>

<robot name="wubble"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">
    
    <!-- Included URDF Files -->
    <include filename="$(find erratic_description)/urdf/erratic_base.xacro" />
    <include filename="$(find smart_arm_description)/urdf/smart_arm.xacro" />
    <include filename="$(find hokuyo_urg_description)/urdf/hokuyo_urg.xacro" />
    <include filename="$(find videre_stoc_description)/urdf/videre_stereo_9cm.xacro" />
    <include filename="$(find chr_6dm_imu_description)/urdf/chrobotics_chr_6dm_imu.urdf.xacro" />
    
    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
        
    <property name="support_radius" value="0.0065" />
    <property name="support_height" value="0.7556" />
    
    <!-- VIDERE ERRATIC MOBILE BASE -->
    <erratic /> 
    
    <!-- CRUST CRAWLER SMART ARM ATTACHMENT -->
    <smart_arm parent="base_top_link" >
        <origin xyz="${top_size_x/2 - 0.0575} 0 ${top_size_z/2 + 0.025}" rpy="0 0 0"/>
    </smart_arm>
    
    <!-- CHR-6dm IMU ATTACHMENT -->
    <chrobotics_chr_6dm_imu name="imu" parent="base_top_link" imu_topic="imu/data" update_rate="100.0" stdev="0.00017" >
        <origin xyz="0.0 0.1 ${top_size_z/2}" rpy="0 0 0" />
    </chrobotics_chr_6dm_imu>
    
    <!-- HOKUYO LASER ATTACHMENT -->
    <joint name="laser_support_joint" type="fixed">
        <origin xyz="${top_size_x/2 - 0.016} 0.02 -${top_size_z/2}" rpy="${M_PI} 0 0" />
        <parent link="base_top_link"/>
        <child link="hokuyo_tilt_link"/>
    </joint>
    
    <link name="hokuyo_tilt_link"> 
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0"
                     iyy="0.01" iyz="0"
                     izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_tilt.stl"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_tilt.stl"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="hokuyo_tilt_joint" type="revolute">
        <origin xyz="-0.019 0 0.043" />
        <parent link="hokuyo_tilt_link" />
        <child link="hokuyo_mount_link" />
        
        <axis xyz="0 1 0" />
        <limit lower="-0.1" upper="0.785398164" effort="100" velocity="12.0" />
        <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-0.1+0.1}" soft_upper_limit="${0.785398164-0.1}" />
        <dynamics damping="50" friction="1"/>
    </joint>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="hokuyo_tilt_trans">
        <actuator name="hokuyo_tilt_motor" />
        <joint name="hokuyo_tilt_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
    <link name="hokuyo_mount_link"> 
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0"
                     iyy="0.01" iyz="0"
                     izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_mount.stl"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_mount.stl"/>
            </geometry>
        </collision>
    </link>
    
    <hokuyo_urg name="tilt_laser" parent="hokuyo_mount_link">
        <origin xyz="0 0 0.023" rpy="0 0 0" />
    </hokuyo_urg>
    
    <!-- VIDERE STOC STEREO CAMERA ATTACHMENT -->
    <joint name="head_support_joint" type="fixed">
        <origin xyz="${top_size_x/2 - 0.17} 0 ${top_size_z/2}" />
        <parent link="base_top_link" />
        <child link="head_support_link" />
    </joint>
    
    <link name="head_support_link"> 
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0.0 0.0 ${support_height/2}" rpy="0 0 0" />
            <inertia    ixx="0.1" ixy="0" ixz="0" 
                        iyy="0.1" iyz="0" 
                        izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 ${support_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 ${support_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="head_pan_support_joint" type="fixed">
        <origin xyz="0 0 ${support_height}" />
        <parent link="head_support_link" />
        <child link="head_pan_link" />
    </joint>
    
    <link name="head_pan_link"> 
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0"
                     iyy="0.01" iyz="0"
                     izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0.018" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_pan.stl"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0.018" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_pan.stl"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="head_pan_joint" type="revolute">
        <origin xyz="0.0135 0 0.058" />
        <parent link="head_pan_link" />
        <child link="head_tilt_link" />
        
        <axis xyz="0 0 1" />
        <limit lower="-1.570796327" upper="1.570796327" effort="100.0" velocity="1.17" />
        <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.570796327+0.1}" soft_upper_limit="${1.570796327-0.1}" />
        <dynamics damping="50" friction="1"/>
    </joint>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="head_pan_trans">
        <actuator name="head_pan_motor" />
        <joint name="head_pan_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
    <link name="head_tilt_link"> 
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0"
                     iyy="0.01" iyz="0"
                     izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_tilt.stl"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_tilt.stl"/>
            </geometry>
        </collision>
    </link>
    
    <joint name="head_tilt_joint" type="revolute">
        <origin xyz="-0.019 0 0.043" />
        <parent link="head_tilt_link" />
        <child link="head_mount_link" />
    
        <axis xyz="0 -1 0" />
        <limit lower="-1.221730476" upper="0.610865238" effort="100.0" velocity="1.17" />
        <safety_controller k_position="100" k_velocity="15.0" soft_lower_limit="${-1.221730476+0.1}" soft_upper_limit="${0.610865238-0.1}" />
        <dynamics damping="50" friction="1"/>
    </joint>
    
    <transmission type="pr2_mechanism_model/SimpleTransmission" name="head_tilt_trans">
        <actuator name="head_tilt_motor" />
        <joint name="head_tilt_joint" />
        <mechanicalReduction>1.0</mechanicalReduction>
    </transmission>
    
    <link name="head_mount_link"> 
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0"
                     iyy="0.01" iyz="0"
                     izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_mount.stl"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <mesh filename="package://wubble_description/meshes/camera_mount.stl"/>
            </geometry>
        </collision>
    </link>
    
    <videre_stereo_9cm name="stoc" parent="head_mount_link" >
        <origin xyz="0 0 0.023" rpy="0 0 0" />
    </videre_stereo_9cm>
    
    <!-- GAZEBO MATERIALS -->
    <gazebo reference="head_support_link">
        <material>Wubble/BrassScratched</material>
    </gazebo>
    
    <gazebo reference="head_pan_link">
        <material>PR2/Black</material>
    </gazebo>
    
    <gazebo reference="head_tilt_link">
        <material>PR2/Black</material>
    </gazebo>
    
    <gazebo reference="head_mount_link">
        <material>PR2/White</material>
    </gazebo>
    
    <gazebo reference="hokuyo_tilt_link">
        <material>PR2/Black</material>
    </gazebo>
    
    <gazebo reference="hokuyo_mount_link">
        <material>SmartArm/GunMetalBrushedAluminum</material>
    </gazebo>
</robot>
