<?xml version="1.0"?>

<robot name="wubble"
    xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
    xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
    xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <!-- Included URDF Files -->
    <include filename="$(find erratic_description)/urdf/erratic_base.xacro" />
    <include filename="$(find smart_arm_description)/urdf/smart_arm.xacro" />
    <include filename="$(find hokuyo_urg_description)/urdf/tilting_hokuyo.xacro" />
    <include filename="$(find videre_stoc_description)/urdf/videre_stoc.xacro" />

    <include filename="$(find pr2_defs)/calibration/default_cal.xml" />
<!--    <include filename="$(find pr2_defs)/defs/materials.urdf.xacro" />    -->

    <!-- Properties (Constants) -->
    <property name="M_PI" value="3.14159"/>
        
    <property name="support_radius" value="0.01" />
    <property name="support_height" value="0.8128" />


    <!-- MACRO INSTANTIATION -->

    <erratic /> 

    <smart_arm parent="base_top_link" />

<!--    <joint name="laser_test_joint" type="fixed">-->
<!--        <origin xyz="0.5 0.0 0.5" />-->
<!--        <parent link="base_top_link" />-->
<!--        <child link="hokuyo_link" />-->
<!--    </joint>-->

    <tilting_hokuyo parent="base_top_link">
        <origin xyz="0.15 0 ${-top_size_z - 0.05}" rpy="${M_PI} 0 0" />
    </tilting_hokuyo>

    <stoc_camera name="stoc" parent="head_pan_link" />
    

    <!-- Special Links -->

    <joint name="head_support_joint" type="fixed">
        <origin xyz="0.0254 0 ${top_size_z/2}" />
        <parent link="base_top_link" />
        <child link="head_support_link" />
    </joint>

    <link name="head_support_link"> 
        <inertial>
            <mass value="0.1"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia    ixx="0.1" ixy="0" ixz="0" 
                        iyy="0.1" iyz="0" 
                        izz="0.1"/>
        </inertial>
        
        <visual>
            <origin xyz="0.0 0.0 ${support_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0.0 0.0 ${support_height/2}" rpy="0 0 0" />
            <geometry>
                <cylinder radius="${support_radius}" length="${support_height}"/>
            </geometry>
        </collision>
    </link>

    <joint name="head_pan_joint" type="revolute">
        <origin xyz="0 0 ${support_height}" />
        <parent link="head_support_link" />
        <child link="head_pan_link" />
        
        <axis xyz="0 0 1" />
<!--        <anchor xyz="0 0 0" />-->
<!--        <limit effort="100" velocity="100" />-->
        <limit lower="0" upper="0" effort="100" velocity="1.0" />
        <dynamics damping="1" friction="1" />
<!--        <safety_controller k_position="100" k_velocity="0.05" soft_lower_limit="${-0.785+0.0}" soft_upper_limit="${1.57-0.0}" />-->
    </joint>

    <transmission type="SimpleTransmission" name="head_pan_trans">
        <actuator name="head_pan_motor" />
        <joint name="head_pan_joint" />
        <mechanicalReduction>6.0</mechanicalReduction>
    </transmission>

    <link name="head_pan_link"> 
        <inertial>
            <mass value="0.01"/>
            <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
        </inertial>
        
        <visual>
            <origin xyz="0 0 0.0127" rpy="0 0 0"/>
            <geometry>
                <box size="${2*support_radius} ${2*support_radius} 0.0254" />
            </geometry>
        </visual>
        
        <collision>
            <origin xyz="0 0 0.0127" rpy="0 0 0"/>
            <geometry>
                <box size="${2*support_radius} ${2*support_radius} 0.0254" />
            </geometry>
        </collision>
    </link>

    <!--        <joint name="stoc_camera_joint" type="fixed">
            <origin xyz="0 0 ${(stoc_height/2)+0.0254}" rpy="0 0 0" />   
            <parent link="${parent}" />
            <child link="stoc_camera_link"/>
        </joint>
-->
    <joint name="head_tilt_joint" type="revolute">
        <origin xyz="0 0 ${0.0254}" rpy="0 0 0" />
        <parent link="head_pan_link"/>
        <child link="stoc_camera_link"/>

        <axis xyz="0 1 0" />
        <limit lower="-0.5" upper="1.00" effort="100" velocity="2.00" />
        <safety_controller k_position="100" k_velocity="0.05" soft_lower_limit="${-0.785+0.0}" soft_upper_limit="${1.57-0.0}" />
        <!-- hold both reference_position and upper/lower for tick-tock, remove reference_positiion after verifying upper/lower works with calibration controllers.  if search velocity in pr2_calibration_controllers.yaml is +, the reference_position is rising, if - then it is falling -->
        <calibration reference_position="-.35" falling="-.35" />
        <dynamics damping="0.008" />
    </joint>    
      
    <transmission type="SimpleTransmission" name="head_tilt_trans">
        <actuator name="head_tilt_motor" />
        <joint name="head_tilt_joint" />
        <mechanicalReduction>3.0</mechanicalReduction>
    </transmission>

    <!-- GAZEBO MATERIALS -->
 
<!--    <gazebo reference="base_laser_link">-->
<!--        <material>PR2/Red</material>-->
<!--    </gazebo>-->

    <gazebo reference="head_support_link">
        <material>Wubble/BrassScratched</material>
    </gazebo>

    <gazebo reference="head_pan_link">
        <material>PR2/Black</material>
    </gazebo>

</robot>
