<?xml version="1.0"?>
<robot name="erratic"
       xmlns:sensor="http://playerstage.sourceforge.net/gazebo/xmlschema/#sensor"
       xmlns:controller="http://playerstage.sourceforge.net/gazebo/xmlschema/#controller"
       xmlns:interface="http://playerstage.sourceforge.net/gazebo/xmlschema/#interface">

    <property name="M_PI" value="3.14159"/>

    <joint name="base_joint" type="fixed">
        <origin xyz="0 0 3" rpy="0 ${M_PI/2} 0"/>
        <parent link="world"/>
        <child link="overhead_cam_link"/>
    </joint>

    <link name="overhead_cam_link">
        <inertial>
          <mass value="0.001" />
          <origin xyz="0 0 0" />
          <inertia ixx="1.0" ixy="0.0" ixz="0.0"
                   iyy="1.0" iyz="0.0"
                   izz="1.0" />
        </inertial>
        
        <visual>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.1 0.1 0.1" />
          </geometry>
        </visual>

        <collision>
          <origin xyz="0 0 0" rpy="0 0 0" />
          <geometry>
            <box size="0.1 0.1 0.1" />
          </geometry>
        </collision>
    </link>

    <property name="image_width" value="1024"/>
    <property name="image_height" value="1024"/>
    <property name="hfov" value="90"/>

    <gazebo reference="overhead_cam_link">
        <sensor:camera name="overhead_cam_sensor">
            <imageSize>${image_width} ${image_height}</imageSize>
            <imageFormat>PF_B8G8R8</imageFormat>
            <hfov>${hfov}</hfov>
            <nearClip>0.1</nearClip>
            <farClip>100</farClip>
            <updateRate>15.0</updateRate>
            <controller:gazebo_ros_camera name="overhead_cam_controller" plugin="libgazebo_ros_camera.so">
                <alwaysOn>true</alwaysOn>
                <updateRate>15.0</updateRate>
                <imageTopicName>overhead_cam/image_raw</imageTopicName>
                <cameraInfoTopicName>overhead_cam/camera_info</cameraInfoTopicName>
                <frameName>overhead_cam_link</frameName>
                <CxPrime>${(image_width+1)/2}</CxPrime>
                <Cx>${(image_width+1)/2}</Cx>
                <Cy>${(image_height+1)/2}</Cy>
                <!-- focal_length = image_width / (2*tan(hfov_radian /2)) BUT tan(45 deg) = 1 -->
                <focal_length>${image_width / 2}</focal_length> 
                <distortion_k1>0</distortion_k1>
                <distortion_k2>0</distortion_k2>
                <distortion_k3>0</distortion_k3>
                <distortion_t1>0</distortion_t1>
                <distortion_t2>0</distortion_t2>
                <interface:camera name="overhead_cam_iface" />
            </controller:gazebo_ros_camera>
        </sensor:camera>
    </gazebo>

    <gazebo reference="overhead_cam_link">
        <material>Gazebo/Black</material>
    </gazebo>

</robot>
