shoulder_pan_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: shoulder_pan_joint
    joint_speed: 1.17
    motor:
        id: 1
        init: 512
        min: 273
        max: 751

shoulder_tilt_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDualAX12
    joint_name: shoulder_tilt_joint
    joint_speed: 1.17
    motor_master:
        id: 2
        init: 512
        min: 717
        max: 126
    motor_slave:
        id: 3

elbow_tilt_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDualAX12
    joint_name: elbow_tilt_joint
    joint_speed: 1.17
    motor_master:
        id: 4
        init: 512
        min: 881
        max: 126
    motor_slave:
        id: 5

wrist_rotate_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: wrist_rotate_joint
    joint_speed: 1.17
    motor:
        id: 6
        init: 512
        min: 1023
        max: 0

finger_right_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: finger_right_joint
    joint_speed: 1.17
    motor:
        id: 7
        init: 676
        min: 512
        max: 724

finger_left_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: finger_left_joint
    joint_speed: 1.17
    motor:
        id: 8
        init: 347
        min: 300
        max: 512

