shoulder_pan_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: shoulder_pan_joint
    joint_speed: 1.17
    motor:
        id: 10
        init: 512
        min: 273
        max: 751

shoulder_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: shoulder_tilt_joint
    joint_speed: 1.17
    motor_master:
        id: 11
        init: 512
        min: 717
        max: 126
    motor_slave:
        id: 12

elbow_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller_dual_motor
        type: JointPositionControllerDual
    joint_name: elbow_tilt_joint
    joint_speed: 1.17
    motor_master:
        id: 13
        init: 512
        min: 126
        max: 881
    motor_slave:
        id: 14

wrist_rotate_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: wrist_rotate_joint
    joint_speed: 1.17
    motor:
        id: 15
        init: 512
        min: 1023
        max: 0

finger_right_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: finger_right_joint
    joint_speed: 1.17
    motor:
        id: 16
        init: 676
        min: 512
        max: 724

finger_left_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: finger_left_joint
    joint_speed: 1.17
    motor:
        id: 18
        init: 347
        min: 300
        max: 512

