laser_tilt_controller:
    controller:
        package: ax12_controller_core
        module: joint_position_controller
        type: JointPositionControllerAX12
    joint_name: hokuyo_tilt_joint
    joint_speed: 1.17
    motor:
        id: 9
        init: 831
        min: 890
        max: 663
