laser_tilt_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: hokuyo_tilt_joint
    joint_speed: 1.17
    motor:
        id: 9
        init: 831
        min: 890
        max: 663
