/* auto-generated by gensrv_java from /home/dhewlett/ros/ua-ros-pkg/ua_experimental/time_series/srv/ConstrainVerb.srv.  Do not edit! */
package ros.pkg.time_series.srv;

import java.nio.ByteBuffer;

public class ConstrainVerb extends ros.communication.Service<ConstrainVerb.Request, ConstrainVerb.Response> 
{

public static String __s_getDataType() { return "time_series/ConstrainVerb"; }
public static String __s_getMD5Sum() { return "49be8694f53a8c92d1ceab539307d10b"; }

public String getDataType() { return ConstrainVerb.__s_getDataType(); }
public String getMD5Sum() { return ConstrainVerb.__s_getMD5Sum(); }

public static class Request extends ros.communication.Message
{

  public java.lang.String verb;
  public java.lang.String[] banned_props;

  public Request() {
 super();
    verb = new java.lang.String();
  banned_props = new java.lang.String[0];

  }
  public static java.lang.String __s_getDataType() { return "time_series/ConstrainVerbRequest"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "string verb\n" + 
    "string[] banned_props\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("49be8694f53a8c92d1ceab539307d10b"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("time_series/ConstrainVerb"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Request clone() {
    Request clone = (Request)super.clone();
      banned_props =  (java.lang.String[])(clone.banned_props.clone());
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      m.put("verb", "java.lang.String");
     m.put("banned_props", "java.lang.String[]");
     return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Request)) throw new RuntimeException("Invalid Type");
    Request __m2 = (Request) __m;
    verb = __m2.verb;
    banned_props = __m2.banned_props;
    }

  int calc_banned_props_array_serialization_len() {
    int l = 0;
    for (int i = 0; i < banned_props.length; i++) 
      l += 4 + banned_props[i].length();
    return l;
  }
  public int serializationLength() 
  {
    int __l = 0;
    __l += 4 + verb.length(); // verb
    __l += 4 + calc_banned_props_array_serialization_len(); // banned_props
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
    Serialization.writeString(bb, verb);
    bb.putInt(banned_props.length);
    for (java.lang.String x : banned_props)
      Serialization.writeString(bb, x);
  }
  public void deserialize(ByteBuffer bb)  {
    verb = Serialization.readString(bb);
     int banned_props_len = bb.getInt();
    banned_props = new java.lang.String[banned_props_len];
    for(int i = 0; i < banned_props_len; i++)
      banned_props[i] = Serialization.readString(bb);
  }
}

public static class Response extends ros.communication.Message
{


  public Response() {
 super();

  }
  public static java.lang.String __s_getDataType() { return "time_series/ConstrainVerbResponse"; }
  public static java.lang.String __s_getMD5Sum() { return ""; }
  public static java.lang.String __s_getMessageDefinition()
  {
    return 
    "\n" + 
    "\n" + 
    "";
  }
  public java.lang.String getDataType() { return __s_getDataType(); }
  public java.lang.String getMD5Sum()   { return __s_getMD5Sum(); }
  public java.lang.String getMessageDefinition() { return __s_getMessageDefinition(); }
  public static java.lang.String __s_getServerMD5Sum() { return ("49be8694f53a8c92d1ceab539307d10b"); }
  public java.lang.String getServerMD5Sum() { return __s_getServerMD5Sum(); }
  public static java.lang.String  __s_getServiceDataType() { return ("time_series/ConstrainVerb"); }
  public java.lang.String getServiceDataType() { return __s_getServiceDataType(); }
  public Response clone() {
    Response clone = (Response)super.clone();
    return clone;
  }

  public static java.util.Map<java.lang.String, java.lang.String> fieldTypes() {
         java.util.HashMap<java.lang.String, java.lang.String> m = new java.util.HashMap<java.lang.String, java.lang.String>  ();      return m;
  }

  public static java.util.Set<java.lang.String> submessageTypes() {
         java.util.HashSet<java.lang.String> s = new java.util.HashSet<java.lang.String>  ();      return s;
  }

  public void setTo(ros.communication.Message __m) {
    if (!(__m instanceof Response)) throw new RuntimeException("Invalid Type");
    Response __m2 = (Response) __m;
    }

  public int serializationLength() 
  {
    int __l = 0;
    return __l;
  }
  public void serialize(ByteBuffer bb, int seq) {
  }
  public void deserialize(ByteBuffer bb)  {
  }
}

public ConstrainVerb.Request createRequest() { return new ConstrainVerb.Request(); }public ConstrainVerb.Response createResponse() { return new ConstrainVerb.Response(); }}

