#
# Software License Agreement (BSD License)
#
# Copyright (c) 2010, Antons Rebguns. All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
#
#  * Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
#  * Redistributions in binary form must reproduce the above
#    copyright notice, this list of conditions and the following
#    disclaimer in the documentation and/or other materials provided
#    with the distribution.
#  * Neither the name of University of Arizona nor the names of its
#    contributors may be used to endorse or promote products derived
#    from this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
# FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
# COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
# INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
# BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
# ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
# POSSIBILITY OF SUCH DAMAGE.
#
# Author: Antons Rebguns
#

"""
CHR-6dm Constants
"""

# Data output scale factors
SCALE_YAW = 0.0109863           # degrees/LSB
SCALE_PITCH = 0.0109863
SCALE_ROLL = 0.0109863
SCALE_YAW_RATE = 0.0137329      # degrees/second/LSB
SCALE_PITCH_RATE = 0.0137329
SCALE_ROLL_RATE = 0.0137329
SCALE_MAG_X = 0.061035          # mGauss/LSB
SCALE_MAG_Y = 0.061035
SCALE_MAG_Z = 0.061035
SCALE_GYRO_X = 0.01812          # degrees/second/LSB
SCALE_GYRO_Y = 0.01812
SCALE_GYRO_Z = 0.01812
SCALE_ACCEL_X = 0.106812        # mg/LSB
SCALE_ACCEL_Y = 0.106812
SCALE_ACCEL_Z = 0.106812

# RX packets
SET_ACTIVE_CHANNELS = 0x80
SET_SILENT_MODE = 0x81
SET_BROADCAST_MODE = 0x82
SET_GYRO_BIAS = 0x83
SET_ACCEL_BIAS = 0x84
SET_ACCEL_REF_VECTOR = 0x85
AUTO_SET_ACCEL_REF = 0x86
ZERO_RATE_GYROS = 0x87
SELF_TEST = 0x88
SET_START_CAL = 0x89
SET_PROCESS_COVARIANCE = 0x8A
SET_MAG_COVARIANCE = 0x8B
SET_ACCEL_COVARIANCE = 0x8C
SET_EKF_CONFIG = 0x8D
SET_GYRO_ALIGNMENT = 0x8E
SET_ACCEL_ALIGNMENT = 0x8F
SET_MAG_REF_VECTOR = 0x90
AUTO_SET_MAG_REF = 0x91
SET_MAG_CAL = 0x92
SET_MAG_BIAS = 0x93
SET_GYRO_SCALE = 0x94
EKF_RESET = 0x95
RESET_TO_FACTORY = 0x96

WRITE_TO_FLASH = 0xA0

GET_DATA = 0x01
GET_ACTIVE_CHANNELS = 0x02
GET_BROADCAST_MODE = 0x03
GET_ACCEL_BIAS = 0x04
GET_ACCEL_REF_VECTOR = 0x05
GET_GYRO_BIAS = 0x06
GET_GYRO_SCALE = 0x07
GET_START_CAL = 0x08
GET_EKF_CONFIG = 0x09
GET_ACCEL_COVARIANCE = 0x0A
GET_MAG_COVARIANCE = 0x0B
GET_PROCESS_COVARIANCE = 0x0C
GET_STATE_COVARIANCE = 0x0D
GET_GYRO_ALIGNMENT = 0x0E
GET_ACCEL_ALIGNMENT = 0x0F
GET_MAG_REF_VECTOR = 0x10
GET_MAG_CAL = 0x11
GET_MAG_BIAS = 0x12

# TX packets
COMMAND_COMPLETE = 0xB0
COMMAND_FAILED = 0xB1
BAD_CHECKSUM = 0xB2
BAD_DATA_LENGTH = 0xB3
UNRECOGNIZED_PACKET = 0xB4
BUFFER_OVERFLOW = 0xB5
STATUS_REPORT = 0xB6
SENSOR_DATA = 0xB7
GYRO_BIAS_REPORT = 0xB8
GYRO_SCALE_REPORT = 0xB9
START_CAL_REPORT = 0xBA
ACCEL_BIAS_REPORT = 0xBB
ACCEL_REF_VECTOR_REPORT = 0xBC
ACTIVE_CHANNEL_REPORT = 0xBD
ACCEL_COVARIANCE_REPORT = 0xBE
MAG_COVARIANCE_REPORT = 0xBF
PROCESS_COVARIANCE_REPORT = 0xC0
STATE_COVARIANCE_REPORT = 0xC1
EKF_CONFIG_REPORT = 0xC2
GYRO_ALIGNMENT_REPORT = 0xC3
ACCEL_ALIGNMENT_REPORT = 0xC4
MAG_REF_VECTOR_REPORT = 0xC5
MAG_CAL_REPORT = 0xC6
MAG_BIAS_REPORT = 0xC7
BROADCAST_MODE_REPORT = 0xC8

CODE_TO_STR = {
    SET_ACTIVE_CHANNELS: "SET_ACTIVE_CHANNELS",
    SET_SILENT_MODE: "SET_SILENT_MODE",
    SET_BROADCAST_MODE: "SET_BROADCAST_MODE",
    SET_GYRO_BIAS: "SET_GYRO_BIAS",
    SET_ACCEL_BIAS: "SET_ACCEL_BIAS",
    SET_ACCEL_REF_VECTOR: "SET_ACCEL_REF_VECTOR",
    AUTO_SET_ACCEL_REF: "AUTO_SET_ACCEL_REF",
    ZERO_RATE_GYROS: "ZERO_RATE_GYROS",
    SELF_TEST: "SELF_TEST",
    SET_START_CAL: "SET_START_CAL",
    SET_PROCESS_COVARIANCE: "SET_PROCESS_COVARIANCE",
    SET_MAG_COVARIANCE: "SET_MAG_COVARIANCE",
    SET_ACCEL_COVARIANCE: "SET_ACCEL_COVARIANCE",
    SET_EKF_CONFIG: "SET_EKF_CONFIG",
    SET_GYRO_ALIGNMENT: "SET_GYRO_ALIGNMENT",
    SET_ACCEL_ALIGNMENT: "SET_ACCEL_ALIGNMENT",
    SET_MAG_REF_VECTOR: "SET_MAG_REF_VECTOR",
    AUTO_SET_MAG_REF: "AUTO_SET_MAG_REF",
    SET_MAG_CAL: "SET_MAG_CAL",
    SET_MAG_BIAS: "SET_MAG_BIAS",
    SET_GYRO_SCALE: "SET_GYRO_SCALE",
    EKF_RESET: "EKF_RESET",
    RESET_TO_FACTORY: "RESET_TO_FACTORY",
    WRITE_TO_FLASH: "WRITE_TO_FLASH",
    
    GET_DATA: "GET_DATA",
    GET_ACTIVE_CHANNELS: "GET_ACTIVE_CHANNELS",
    GET_BROADCAST_MODE: "GET_BROADCAST_MODE",
    GET_ACCEL_BIAS: "GET_ACCEL_BIAS",
    GET_ACCEL_REF_VECTOR: "GET_ACCEL_REF_VECTOR",
    GET_GYRO_BIAS: "GET_GYRO_BIAS",
    GET_GYRO_SCALE: "GET_GYRO_SCALE",
    GET_START_CAL: "GET_START_CAL",
    GET_EKF_CONFIG: "GET_EKF_CONFIG",
    GET_ACCEL_COVARIANCE: "GET_ACCEL_COVARIANCE",
    GET_MAG_COVARIANCE: "GET_MAG_COVARIANCE",
    GET_PROCESS_COVARIANCE: "GET_PROCESS_COVARIANCE",
    GET_STATE_COVARIANCE: "GET_STATE_COVARIANCE",
    GET_GYRO_ALIGNMENT: "GET_GYRO_ALIGNMENT",
    GET_ACCEL_ALIGNMENT: "GET_ACCEL_ALIGNMENT",
    GET_MAG_REF_VECTOR: "GET_MAG_REF_VECTOR",
    GET_MAG_CAL: "GET_MAG_CAL",
    GET_MAG_BIAS: "GET_MAG_BIAS",
    
    COMMAND_COMPLETE: "COMMAND_COMPLETE",
    COMMAND_FAILED: "COMMAND_FAILED",
    BAD_CHECKSUM: "BAD_CHECKSUM",
    BAD_DATA_LENGTH: "BAD_DATA_LENGTH",
    UNRECOGNIZED_PACKET: "UNRECOGNIZED_PACKET",
    BUFFER_OVERFLOW: "BUFFER_OVERFLOW",
    STATUS_REPORT: "STATUS_REPORT",
    SENSOR_DATA: "SENSOR_DATA",
    GYRO_BIAS_REPORT: "GYRO_BIAS_REPORT",
    GYRO_SCALE_REPORT: "GYRO_SCALE_REPORT",
    START_CAL_REPORT: "START_CAL_REPORT",
    ACCEL_BIAS_REPORT: "ACCEL_BIAS_REPORT",
    ACCEL_REF_VECTOR_REPORT: "ACCEL_REF_VECTOR_REPORT",
    ACTIVE_CHANNEL_REPORT: "ACTIVE_CHANNEL_REPORT",
    ACCEL_COVARIANCE_REPORT: "ACCEL_COVARIANCE_REPORT",
    MAG_COVARIANCE_REPORT: "MAG_COVARIANCE_REPORT",
    PROCESS_COVARIANCE_REPORT: "PROCESS_COVARIANCE_REPORT",
    STATE_COVARIANCE_REPORT: "STATE_COVARIANCE_REPORT",
    EKF_CONFIG_REPORT: "EKF_CONFIG_REPORT",
    GYRO_ALIGNMENT_REPORT: "GYRO_ALIGNMENT_REPORT",
    ACCEL_ALIGNMENT_REPORT: "ACCEL_ALIGNMENT_REPORT",
    MAG_REF_VECTOR_REPORT: "MAG_REF_VECTOR_REPORT",
    MAG_CAL_REPORT: "MAG_CAL_REPORT",
    MAG_BIAS_REPORT: "MAG_BIAS_REPORT",
    BROADCAST_MODE_REPORT: "BROADCAST_MODE_REPORT",
}

