VerbInstance verb
oomdp_msgs/MDPState start_state # get this from calling initialize
int32 execution_limit  # max number of steps in execution before failure
---
bool planning_success
int64 planning_time
int32 execution_length
bool execution_success